name: Build zips

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Zip plugin
        run: |
          cd plugin
          zip -r ../ai-auto-summary-ondemand-patched.zip ai-auto-summary-ondemand-patched
      - name: Zip backend-php
        run: |
          cd backend-php
          zip -r ../ai-summarize-php.zip ai-summarize
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            ai-auto-summary-ondemand-patched.zip
            ai-summarize-php.zip
      - name: Create Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ai-auto-summary-ondemand-patched.zip
            ai-summarize-php.zip
